### ISSUE TITLE
Python 3.7 issue in 3.0.3 release - Due to PEP479

### ISSUE THREAD

**Issue by SteveClement** [vaab/gitchangelog#107]
It seems **gitchangelog** is not happy with Python 3.7 when install via pip.

The 3.0.3 release seems to not include the patch made in d72a0f0
When installed from the master branch of the repo, it works.

~~Or Linux Brew does something to it. Not sure, will do more testing and eventually fix whatever needs fixing.~~

Seems the same issue as here: https://github.com/googleapis/google-cloud-python/issues/5282

Does work in a Python 3.6 virtualenv. (I initially thought the venv was the the issue, it is not)
```bash
 ~/MISP_Main/MISP-Official  2.4 ● $ mkvirtualenv -p python3 gitchangelog
Running virtualenv with interpreter /home/linuxbrew/.linuxbrew/bin/python3
Using base prefix '/home/linuxbrew/.linuxbrew/bin/../Cellar/python/3.7.0'
/usr/lib/python3/dist-packages/virtualenv.py:1086: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /home/steve/.virtualenvs/gitchangelog/bin/python3.7
Also creating executable in /home/steve/.virtualenvs/gitchangelog/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/steve/.virtualenvs/gitchangelog/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/steve/.virtualenvs/gitchangelog/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/steve/.virtualenvs/gitchangelog/bin/preactivate
virtualenvwrapper.user_scripts creating /home/steve/.virtualenvs/gitchangelog/bin/postactivate
virtualenvwrapper.user_scripts creating /home/steve/.virtualenvs/gitchangelog/bin/get_env_details
(gitchangelog)  ~/MISP_Main/MISP-Official 2.4 ● $ pip install gitchangelog   
Collecting gitchangelog
  Using cached https://files.pythonhosted.org/packages/f7/a9/5bed4379887ad2092e52ba8e22ed491092d4e71fb3464d700d75577d31d9/gitchangelog-3.0.3-py2.py3-none-any.whl
Installing collected packages: gitchangelog
Successfully installed gitchangelog-3.0.3
(gitchangelog)  ✘ ~/MISP_Main/MISP-Official 2.4 ● $ gitchangelog -d
Error: Exception while running 'gitchangelog':
  | Traceback (most recent call last):
  |   File "/home/steve/.virtualenvs/gitchangelog/lib/python3.7/site-packages/gitchangelog/gitchangelog.py", line 615, in read
  |     raise StopIteration
  | StopIteration
  | 
  | The above exception was the direct cause of the following exception:
  | 
  | Traceback (most recent call last):
  |   File "/home/steve/.virtualenvs/gitchangelog/lib/python3.7/site-packages/gitchangelog/gitchangelog.py", line 1963, in main
  |     log_encoding=log_encoding,
  |   File "/home/steve/.virtualenvs/gitchangelog/lib/python3.7/site-packages/gitchangelog/gitchangelog.py", line 1649, in changelog
  |     first_version = next(versions)
  |   File "/home/steve/.virtualenvs/gitchangelog/lib/python3.7/site-packages/gitchangelog/gitchangelog.py", line 1588, in versions_data_iter
  |     for commit in commits:
  |   File "/home/steve/.virtualenvs/gitchangelog/lib/python3.7/site-packages/gitchangelog/gitchangelog.py", line 1234, in log
  |     for key in GIT_FORMAT_KEYS]))
  |   File "/home/steve/.virtualenvs/gitchangelog/lib/python3.7/site-packages/gitchangelog/gitchangelog.py", line 1234, in <listcomp>
  |     for key in GIT_FORMAT_KEYS]))
  | RuntimeError: generator raised StopIteration
(gitchangelog)  ✘ ~/MISP_Main/MISP-Official  2.4 ● $
```

**Comment by SteveClement** [comment]
Hmmm, I just noticed that this was already fixed in https://github.com/vaab/gitchangelog/commit/d72a0f099d45ff03be7017926ef73a1ef3f7cf90

**Comment by whoiswes** [comment]
When will this fix be released?

**Comment by vaab** [comment]
I'll have a look tomorrow with the objective of a quick release of this fix in mind. Sorry for the delays :-)

**Comment by vaab** [comment]
I've release ``3.0.4`` on pypi with the old fix. Tests are also upgraded to include ``3.7`` tests. Sorry for the unjustified delay on this. And many thanks for the constant feedback and the pokes to remind me about that :-)

**Comment by whoiswes** [comment]
Thanks @vaab, I'll give it a go, appreciate the quick response!
