### ISSUE TITLE
Exception with FileInsertIntoFirstRegexMatch

### ISSUE THREAD

**Issue by jsandovalc** [vaab/gitchangelog#121]
Hi everyone.

I just installed gitchangelog and I'm tuning the default config file. Right now I uncommented this:

```
publish = FileInsertIntoFirstRegexMatch(
    "CHANGELOG.rst",
    r'/(?P<rev>[0-9]+\.[0-9]+(\.[0-9]+)?)\s+\([0-9]+-[0-9]{2}-[0-9]{2}\)\n--+\n/',
    idx=lambda m: m.start(1)
)
```

But I'm getting this exception:

```
Traceback (most recent call last):
  File "/home/ark/.local/share/virtualenvs/facture2-dyGMeNLV/bin/gitchangelog", line 10, in <module>
    sys.exit(main())
  File "/home/ark/.local/share/virtualenvs/facture2-dyGMeNLV/lib/python3.7/site-packages/gitchangelog/gitchangelog.py", line 1945, in main
    fail_if_not_present=False)
  File "/home/ark/.local/share/virtualenvs/facture2-dyGMeNLV/lib/python3.7/site-packages/gitchangelog/gitchangelog.py", line 347, in load_config_file
    exec(code, config)  ## pylint: disable=exec-used
  File "/home/ark/workspace/facture2/.gitchangelog.rc", line 243, in <module>
    publish = FileInsertIntoFirstRegexMatch(
NameError: name 'FileInsertIntoFirstRegexMatch' is not defined
```

My python version is `3.7.3` and my gitchangelog version is `3.0.4`.

Thanks for any help provided

**Comment by gabrielkoo** [comment]
It should have been `FileInsertAtFirstRegexMatch` instead.

**Comment by jsandovalc** [comment]
Thanks, I already configured it. By the way, that's how it's in the example config, I just uncommented.

Anyway, I'll close this issue.
