### ISSUE TITLE
Typecast Exception in committer_date_timestamp

### ISSUE THREAD

**Issue by gthieleb** [vaab/gitchangelog#79]
Error: Exception while running 'gitchangelog':
	  | Traceback (most recent call last):
	  |   File "/home/gt0015/Development/Python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog/gitchangelog.py", line 1967, in main
	  |     log_encoding=log_encoding,
	  |   File "/home/gt0015/Development/Python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog/gitchangelog.py", line 1653, in changelog
	  |     first_version = next(versions)
	  |   File "/home/gt0015/Development/Python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog/gitchangelog.py", line 1553, in versions_data_iter
	  |     for tag in repository.tags(contains=revs[-1] if revs else None)
	  |   File "/home/gt0015/Development/Python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog/gitchangelog.py", line 1197, in tags
	  |     key=lambda x: int(x.committer_date_timestamp))
	  |   File "/home/gt0015/Development/Python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog/gitchangelog.py", line 1197, in <lambda>
	  |     key=lambda x: int(x.committer_date_timestamp))
	  | ValueError: invalid literal for int() with base 10: ''

**Comment by gthieleb** [comment]
⟫ gitchangelog -v (from pip)
	3.0.1

**Comment by vaab** [comment]
Hi, thanks for your interest in gitchangelog. 
- is it systematic ?
- Can you give us your git version ? 
- and probably give us the result of:

    while read tag; do git log -n 1 --format="$tag:%ct" $tag ; done < <(git tag)

- python version ? system ?
- do you reproduce it on python v2/v3 ?
- any specific way to reproduce it on my system ? (is the repository public ?)

**Comment by vaab** [comment]
For as long as I can tell, this means that ``git log`` output is not correctly parsed upon at least one tag commit.

**Comment by gthieleb** [comment]
Hi sorry for the delay. 

    is it systematic ?

    No. Only specific repo.

    Can you give us your git version ?

    2.7.4

    and probably give us the result of:

    while read tag; do git log -n 1 --format="$tag:%ct" $tag ; done < <(git tag)

```
> while read tag; do git log -n 1 --format="$tag:%ct" $tag ; done < <(git tag)
v0.9:1484215501
v1.0:1486574175
v1.1:1487248439
v1.1.0:1487249084
v1.1.2:1487774246
v1.1.3:1488874649
v1.1.4:1491240995
v1.1.7:1492499101

```

    python version ? system ?

    2.7.12 / ubuntu 16.04 x86_64

    do you reproduce it on python v2/v3 ?

    only 2 

    any specific way to reproduce it on my system ? (is the repository public ?)

    unfortunately not.

**Comment by gthieleb** [comment]
My idea was that version format like v0.9 raise this exception as other have this format: `[0-9].[0-9].[0-9]`.
But this does not seem to solve the issue.

Current tags:

> v0.9.0
> v1.0.0
> v1.1.0
> v1.1.2
> v1.1.3
> v1.1.4
> v1.1.6
> v1.1.7

	$ gitchangelog --debug
	Error: Exception while running 'gitchangelog':
	  | Traceback (most recent call last):
	  |   File "/home/gt0015/development/python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog-3.0.3-py2.7.egg/gitchangelog/gitchangelog.py", line 1963, in main
	  |     log_encoding=log_encoding,
	  |   File "/home/gt0015/development/python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog-3.0.3-py2.7.egg/gitchangelog/gitchangelog.py", line 1649, in changelog
	  |     first_version = next(versions)
	  |   File "/home/gt0015/development/python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog-3.0.3-py2.7.egg/gitchangelog/gitchangelog.py", line 1549, in versions_data_iter
	  |     for tag in repository.tags(contains=revs[-1] if revs else None)
	  |   File "/home/gt0015/development/python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog-3.0.3-py2.7.egg/gitchangelog/gitchangelog.py", line 1193, in tags
	  |     key=lambda x: int(x.committer_date_timestamp))
	  |   File "/home/gt0015/development/python/envs/acdc/local/lib/python2.7/site-packages/gitchangelog-3.0.3-py2.7.egg/gitchangelog/gitchangelog.py", line 1193, in <lambda>
	  |     key=lambda x: int(x.committer_date_timestamp))
	  | ValueError: invalid literal for int() with base 10: ''

**Comment by gthieleb** [comment]
^^ using latest pull

**Comment by gthieleb** [comment]
Seems gitchangelog has a hard time to handle simple (non-annotated) tags. These kind of tags do not have a `authors` or `committers` timestamp, that's where there error in line `1193` raises. Do you think keep this open as a bug or worth a note in the docs?

**Comment by vaab** [comment]
There's obviously a bug, but you don't give me enough information for me to investiguate. It is definitively not a problem about non-annotated tags not supported (at least not that simple) as I never use them in all my projects using ``gitchangelog``.

You can try successive calls to:

    gitchangelog TAG1..TAG2

to see if a particular tag is problematic.

You can definitively check which tag you have are annotated and which are not. And print informations about them.

**Comment by gthieleb** [comment]
This is the problematic tag:

	$ git show v1.1.6
	tag v1.1.6
	Tagger: Gunnar Thielebein <gunnar.thielebein@etomer.com>
	Date:   Wed Apr 12 21:03:35 2017 +0200

	tag for version bump
	__version__ = '1.1.6'

This is another tag:

	$ git show v1.1.4
	tag v1.1.4
	Tagger: Gunnar Thielebein <gunnar.thielebein@etomer.com>
	Date:   Mon Apr 3 19:37:17 2017 +0200

	bump version

	commit 056394fd557f2e7b8a5a0509064e80c981108ef1
	Author: Gunnar Thielebein <gunnar.thielebein@etomer.com>
	Date:   Mon Apr 3 19:36:35 2017 +0200

	    bump version

	diff --git a/__init__.py b/__init__.py
	index 7bb021e..bc50bee 100644
	--- a/__init__.py
	+++ b/__init__.py

Seems I forgot to reference a commit in the first tag. But what is the main difference between these tags?
I wonder how I've created `v1.1.6`. Sorry I am new to git tagging.

**Comment by vaab** [comment]
May I ask you to give us the result of:
    git cat-file -p TAG
On both valid and buggy tag ?
