### ISSUE TITLE
example of command-line call - explicitly describe positional argument `revlist`

### ISSUE THREAD

**Issue by frantret** [vaab/gitchangelog#84]
Hi @vaab,

Thank you very much for your very interesting project. I plan to use it at work, and to learn from your code, since I am a Python beginner.

I could install it, but soon was lost with the help message from `gitchangelog -h`: I find it unclear what the `revlist` positional argument is supposed to be. Is it a text file created by piping `git log`?* Is it the log as a series of quoted, space-separated arguments?** Should I feed gitchangelog with stdin? Is gitchangelog supposed to get the `revlist` itself by invoking `git log`?

So I read the `README` again, and found no explicit example of command-line call of your tool.

Could you please give me a hint?

Thank you in advance

Frantret

* error: Revision 'chg.txt' is not valid.

** error: Revision '* 95275bf (HEAD -> develop) Logging / debug: removed useless logging.' is not valid.

**Comment by vaab** [comment]
Thanks for your feedback. Indeed, we need to be more explicit about revlist. It is a git syntax terminology and refers to n commit arguments (same as *commits* argument of ``git rev-list``). Thus, your third try should be the working one.

Can you use ``--debug`` to let the traceback being printed. Will figure out what can be improved in the code or in the documentation to make things more straightforward.

**Comment by frantret** [comment]
Sorry I should have put the output of the debug mode in the first place :)

`6771a90` and `95275bf` are in my repo two valid revision identifiers. `git diff 6771a90..95275bf` yields a correct diff.

```
$ gitchangelog -d 6771a90..95275bf
Error: Exception while running 'gitchangelog':
  | Traceback (most recent call last):
  |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1963, in main
  |     log_encoding=log_encoding,
  |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1649, in changelog
  |     first_version = next(versions)
  |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1588, in versions_data_iter
  |     for commit in commits:
  |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1220, in log
  |     plog.stdin.close()
  |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 628, in close
  |     return self._file.close()
  | OSError: [Errno 22] Invalid argument

$ python --version
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)

$ gitchangelog -v
3.0.3

$ git --version
git version 2.12.2.windows.2
```

I use Git for Windows' Bash terminal.

**Comment by vaab** [comment]
May I have access to this repository ? I'd like to make some tests. This is probably a bug I'd like to remove.

**Comment by frantret** [comment]
I just sent you an email with enclosure. Let me know if it doesn't reach you.

**Comment by vaab** [comment]
Thanks, I'm experimenting with your repository. As for now, I'm trying to reproduce your bug without success with ``2.7``, ``3.5``, ``3.6``, 32bit and 64bit version. Using: ``gitchangelog -d 6771a90..95275bf``. To be noted: I'm on ``git 2.11.1.windows.1`` which is different from your version, and standard python (not anaconda). I'll keep you informed if I manage to reproduce it. I'm testing on ``Windows 7`` under virtualbox.

**Comment by vaab** [comment]
Tried latest version of ``miniconda`` on ``python 3.6.0`` (arch: x64) ... still no success in reproducing your issue.

**Comment by frantret** [comment]
Thanks for your tests. I did some more. I guess something is wrong in my configuration (PATH?).

Git Bash, Anaconda

    $ gitchangelog -d 6771a90..95275bf
    Error: Exception while running 'gitchangelog':
      | Traceback (most recent call last):
      |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1963, in main
      |     log_encoding=log_encoding,
      |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1649, in changelog
      |     first_version = next(versions)
      |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1588, in versions_data_iter
      |     for commit in commits:
      |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1220, in log
      |     plog.stdin.close()
      |   File "c:\programs\anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 628, in close
      |     return self._file.close()
      | OSError: [Errno 22] Invalid argument

    $ python --version
    Python 3.6.0 :: Anaconda 4.3.1 (64-bit)

    $ gitchangelog -v
    3.0.3

    $ git --version
    git version 2.13.0.windows.1

Git Bash, standard Python

    $ /e/PortableApps/Python/python.exe /c/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py -d 6771a90..95275bf
    Error: Exception while running 'gitchangelog':
      | Traceback (most recent call last):
      |   File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1963, in main
      |     log_encoding=log_encoding,
      |   File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1649, in changelog
      |     first_version = next(versions)
      |   File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1588, in versions_data_iter
      |     for commit in commits:
      |   File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1220, in log
      |     plog.stdin.close()
      |   File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 628, in close
      |     return self._file.close()
      | OSError: [Errno 22] Invalid argument
    Traceback (most recent call last):
      File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1963, in main
        log_encoding=log_encoding,
      File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1649, in changelog
        first_version = next(versions)
      File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1588, in versions_data_iter
        for commit in commits:
      File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1220, in log
        plog.stdin.close()
      File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 628, in close
        return self._file.close()
    OSError: [Errno 22] Invalid argument

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1998, in <module>
        main()
      File "C:/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py", line 1990, in main
        exit(255)
    NameError: name 'exit' is not defined

    $ /e/PortableApps/Python/python.exe --version
    Python 3.6.1

    $ /e/PortableApps/Python/python.exe /c/Programs/Anaconda3/lib/site-packages/gitchangelog/gitchangelog.py -v
    3.0.3

    $ git --version
    git version 2.13.0.windows.1

Windows CMD prompt, Anaconda

    > C:\Programs\Anaconda3\python.exe C:\Programs\Anaconda3\Lib\site-packages\gitchangelog\gitchangelog.py -d 6771a90..95275bf
    Error: Exception while running 'gitchangelog':
      | Traceback (most recent call last):
      |   File "C:\Programs\Anaconda3\Lib\site-packages\gitchangelog\gitchangelog.py", line 1963, in main
      |     log_encoding=log_encoding,
      |   File "C:\Programs\Anaconda3\Lib\site-packages\gitchangelog\gitchangelog.py", line 1649, in changelog
      |     first_version = next(versions)
      |   File "C:\Programs\Anaconda3\Lib\site-packages\gitchangelog\gitchangelog.py", line 1588, in versions_data_iter
      |     for commit in commits:
      |   File "C:\Programs\Anaconda3\Lib\site-packages\gitchangelog\gitchangelog.py", line 1220, in log
      |     plog.stdin.close()
      |   File "C:\Programs\Anaconda3\Lib\site-packages\gitchangelog\gitchangelog.py", line 628, in close
      |     return self._file.close()
      | OSError: [Errno 22] Invalid argument

    > C:\Programs\Anaconda3\python.exe --version
    Python 3.6.0 :: Anaconda 4.3.1 (64-bit)

    > C:\Programs\Anaconda3\python.exe C:\Programs\Anaconda3\Lib\site-packages\gitchangelog\gitchangelog.py -v
    3.0.3

    > C:\Programs\Git\bin\git.exe --version
    git version 2.13.0.windows.1

Windows CMD prompt, standard Python

    > E:\Python\python.exe C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py -d 6771a90..95275bf
    Error: Exception while running 'gitchangelog':
      | Traceback (most recent call last):
      |   File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1963, in main
      |     log_encoding=log_encoding,
      |   File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1649, in changelog
      |     first_version = next(versions)
      |   File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1588, in versions_data_iter
      |     for commit in commits:
      |   File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1220, in log
      |     plog.stdin.close()
      |   File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 628, in close
      |     return self._file.close()
      | OSError: [Errno 22] Invalid argument
    Traceback (most recent call last):
      File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1963, in main
        log_encoding=log_encoding,
      File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1649, in changelog
        first_version = next(versions)
      File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1588, in versions_data_iter
        for commit in commits:
      File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1220, in log
        plog.stdin.close()
      File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 628, in close
        return self._file.close()
    OSError: [Errno 22] Invalid argument

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1998, in <module>
        main()
      File "C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py", line 1990, in main
        exit(255)
    NameError: name 'exit' is not defined

    > E:\Python\python.exe --version
    Python 3.6.1

    > E:\Python\python.exe C:\Programs\Anaconda3\lib\site-packages\gitchangelog\gitchangelog.py -v
    3.0.3

    > C:\Programs\Git\bin\git.exe --version
    git version 2.13.0.windows.1
